/*
    (c) 2016 Microchip Technology Inc. and its subsidiaries. You may use this
    software and any derivatives exclusively with Microchip products.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION
    WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.

    MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE
    TERMS.
*/

#ifndef _HEARTRATE_H
#define	_HEARTRATE_H

/**
  Section: Included Files
 */

#include <stdint.h>
#include "max30100.h"

/**
  Section: Macro Declarations
 */

#define DEFAULT_MODE            MAX30100_HR_ONLY
#define DEFAULT_HIRES_SET       ENABLED
#define DEFAULT_SAMP_RATE       MAX30100_SR50
#define DEFAULT_PWIDTH          MAX30100_PW200
#define DEFAULT_IR_CURRENT      MAX30100_I0
#define DEFAULT_RED_CURRENT     MAX30100_I0
#define SPO2_INTERRUPT_EN       ENABLED   
#define HR_INTERRUPT_EN         ENABLED
#define TEMP_INTERRUPT_EN       ENABLED 
#define FIFO_INTERRUPT_EN       ENABLED


/**
  Section: Driver APIs
 */

void HeartRate_readSensors(void);
uint16_t HeartRate_getIRdata(void);
uint16_t HeartRate_getREDdata(void);
float HeartRate_getTemperature(void);

#endif // _HEARTRATE_H
